version: 1.0.{build}

image: Visual Studio 2022

configuration: Release

before_build:
  - echo "Restoring NuGet packages..."
  - nuget restore

build:
  project: TestApp.sln
  verbosity: minimal

after_build:
  - echo "Copying artifacts to local directory..."
  - xcopy Release\TestApp.exe C:\help\to\deploy\ /Y

artifacts:
  - path: Release\*.exe
    name: TestAppExecutable