name: Deploy to Local Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build project
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Deploy to Local Server
      run: |
        scp ./build/your_executable user@server-ip:/path/to/deploy/
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
